name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: get step 6
      id: get-step-6
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: get step 6
        setup-command: ''
        command: echo "$(cat ./.github/steps/-step.txt)"
        input: ''
        expected-output: 6|X
        comparison-method: regex
        timeout: 10
        max-score: 5
    - name: get step 2
      id: get-step-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: get step 2
        setup-command: ''
        command: echo "$(cat ./.github/steps/-step.txt)"
        input: ''
        expected-output: '2'
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: get step 3
      id: get-step-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: get step 3
        setup-command: ''
        command: echo "$(cat ./.github/steps/-step.txt)"
        input: ''
        expected-output: '3'
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: get step 4
      id: get-step-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: get step 4
        setup-command: ''
        command: echo "$(cat ./.github/steps/-step.txt)"
        input: ''
        expected-output: '4'
        comparison-method: exact
        timeout: 10
    - name: get step 5
      id: get-step-5
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: get step 5
        setup-command: ''
        command: echo "$(cat ./.github/steps/-step.txt)"
        input: ''
        expected-output: '5'
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GET-STEP-6_RESULTS: "${{steps.get-step-6.outputs.result}}"
        GET-STEP-2_RESULTS: "${{steps.get-step-2.outputs.result}}"
        GET-STEP-3_RESULTS: "${{steps.get-step-3.outputs.result}}"
        GET-STEP-4_RESULTS: "${{steps.get-step-4.outputs.result}}"
        GET-STEP-5_RESULTS: "${{steps.get-step-5.outputs.result}}"
      with:
        runners: get-step-6,get-step-2,get-step-3,get-step-4,get-step-5
